KeunSori/KeunSori-Web

- .github/workflows/eslint.yml
- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.cjs
- eslint.config.js
- package-lock.json
- package.json
- src/App.tsx
- src/main.tsx
- 프로젝트 세팅 마무리
- closed #1 
- 깃허브 린트 및 액션, 라이브러리 설치
- node가 18버전 이상이여야함
-
> Feature: 초기 세팅하기

- eslint.config.js
- src/App.tsx
- src/pages/ContactPage.tsx
- src/pages/HomePage.tsx
- src/pages/LoginPage.tsx
- src/pages/SignUpPage.tsx
- src/pages/UserPage.tsx
없애기
- deploy가 안되는이슈
-
-eslint 변경
-import react 없앰ㄱ
> fix: react import 없앰

- eslint.config.js
- src/App.tsx
- src/pages/ContactPage.tsx
- src/pages/HomePage.tsx
- src/pages/LoginPage.tsx
- src/pages/SignUpPage.tsx
- src/pages/UserPage.tsx
- src/styles/GlobalStyle.tsx
> Fix: 리액트 오류 수정

- src/api/auth.ts
- src/api/axiosInstance.ts
- src/components/Login/LoginForm.tsx
- src/contexts/AuthContext.tsx
- src/utils/jwt.ts
access token, refresh token 모두 local 에 저장(임시)
곧 httpOnly cookie 방식으로 바꿀거임
일단 로그인은 됩니다!
- 로그인 기능이 개판이라 작동하게 만들어뒀습니다
- Fix: 로그인 수정 #22 
- 로그인 수정했습니다.
- 지금은 refresh token 처리가 좀 애매할 수 있습니다.
- 로그인 동작함
> Fix: 로그인 수정

- src/components/Book/Application/ApplicationBook.tsx
- src/components/Book/Application/Button.tsx
- src/components/Book/Application/CalenderStyles.tsx
- src/components/Book/Application/Reservation.tsx
- src/components/Book/CurrentBook.tsx
- src/components/Book/MyNotion.tsx
- src/components/Book/Notion.tsx
- src/components/Book/OutContainer.tsx
- src/components/mobile/useIsMobile.tsx
- src/components/navBar/navBar.tsx
- src/components/navBar/navBar2.tsx
- src/pages/BookPage.tsx
- src/styles/GlobalStyle.tsx
- src/utils/jwt.ts
- 모바일 뷰 작성
- 급하게 없음 ㅜㅜ
- 모바일 뷰등 오류 수정
> Feat: 모바일 뷰 작성

- src/components/Book/Application/ApplicationBook.tsx
- src/components/Book/Application/Button.tsx
- src/components/Book/Application/CalenderStyles.tsx
- src/components/Book/Application/DropBox.tsx
- src/components/Book/Application/Reservation.tsx
- src/components/Book/MyNotion.tsx
- src/components/Book/Notion.tsx
- src/pages/BookPage.tsx
- src/styles/GlobalStyle.tsx
- vercel.json
> Feat: 모바일 뷰 및 여러 사항

- vercel.json
> Hotfix: 버셀 배포

- src/api/axiosInstance.ts
- src/utils/jwt.ts
> Fix: util / error

- src/components/SignUp/SignUpForm.tsx
> Style: 비밀번호 숨기기

- src/App.tsx
- (이곳에 PR을 작성한 이유를 간략하게 적어주세요.)
> Fix: 일단 프로텍트 라우트를 끔

- src/contexts/AuthContext.tsx
500 이슈로 임시 로그아웃 구현
- /logout 500 이슈로
> Fix: 임시 로그아웃

- src/App.tsx
- src/components/Book/Application/Reservation.tsx
- src/components/Book/Application/styles/Button.tsx
- src/components/Book/Application/styles/Times.tsx
- src/pages/BookPage.tsx
- time slot이 10시까지 안보이는 오류가 있엇음
- closed #47 
- flex: justify 에서 속성이 center로 들어간 것이 문제여서 flex start로 고침
-없음
> Fix: time slots 문제 해결

- src/components/Login/LoginForm.tsx
- src/components/SignUp/SignUpForm.tsx
- src/pages/LoginPage.tsx
- src/pages/SignUpPage.tsx
- 
- 
- 로그인, 회원가입 페이지 모바일 뷰 만듦
- 늦어서 미안합니다
-
> Style: 로그인/회원가입 모바일뷰

- src/components/Book/Application/ApplicationBook.tsx
- src/components/BookMange/BasicManage/BasicManage.tsx
- src/components/BookMange/DateMange/DateManage.tsx
- src/components/BookMange/DateMange/ManageNotion.tsx
- 리팩토링 제대로 적용 안된거 수정
- #57 
- rename 놓친 거 고침
- 진짜 정신 못 차리네
- 문제 없음
> Fix: refactoring conflict

- src/api/Instance/authApi.ts
- src/api/Instance/baseApi.ts
- src/components/Login/LoginForm.tsx
- src/contexts/AuthContext.tsx
- src/utils/jwt.ts
- 일반/관리자 사용자에게 각각 다른 페이지를 제공함
- #60 closed
- 일반/관리자 사용자에게 각각 다른 페이지를 제공함
- 원시적인 로직이라 나중에 수정해야함
- 일단 됨
> Feat: 사용자 유형 구분

- src/components/Book/Application/ApplicationBook.tsx
- src/components/Book/Application/Reservation.tsx
- src/components/Book/Time.ts
- src/components/BookMange/BasicManage/DayNotion.tsx
- src/components/BookMange/BasicManage/weekData.ts
- src/components/navBar/navBar3.tsx
- 기본값이 today 였는데 뺏음
- closed #62 
- date Atom을 빼주고 null 값으로 처리
- 없음
- 좋음
> Fix: 달력 기본값을 뺌

- src/api/Instance/authApi.ts
- src/api/Instance/baseApi.ts
> Chore: api 주소 관련

- src/api/Instance/authApi.ts
- src/api/Instance/baseApi.ts
- api를 환경변수 처리 하였습니다
- closed #67 
- api-> 환경변수처리
- 다들 .env 파일 추가하시길..
> Chore: 환경변수 처리

- src/components/Book/Application/ApplicationBook.tsx
- src/components/Book/Application/ReservationModal.tsx
- src/components/BookMange/BasicManage/BasicManage.tsx
- src/components/BookMange/DateMange/DateManage.tsx
- src/components/BookMange/ManageModal.tsx
- 모달창을 페이지 별로 만들었습니다
- closed #68 
- 모달 창 기능에 맞게 배피
> Feat: 모달창 만들기

- src/components/Book/Application/styles/Button.tsx
- src/components/Book/Current/NotionContainer.tsx
- src/components/BookMange/BasicManage/BasicManage.tsx
- src/components/BookMange/DropBoxStyle.tsx
- src/components/Nav.tsx
- 디자인 피드백 반영
- closed #64 
- 패딩 및 폰트 변경 사항 있음
- 특별히 없음
> Style: 피드백 반영

- src/components/Manage/ApprovalTable.tsx
- src/components/Manage/DynamicTable.tsx
- src/pages/ManagePage.tsx
- 
- 
- ManagePage 모바일 뷰 설정
- 
- 브라우저 모바일 도구 기준으론 잘 보임
> Feat: 모바일 뷰, 스크롤 추가

- src/components/Book/Application/ApplicationBook.tsx
- src/components/Book/Application/ReservationModal.tsx
- src/components/ModalStyle.tsx
- src/utils/instrumentUtils.ts
- 예약 확인 세부 사항 추가
- closed #75
-  모달안 내용 변경 및 유틸 추가 그리고 슬롯 보일때 조건 추가
> Feat: 모달 세부기능 추가

- src/components/BookMange/BasicManage/DayNotion.tsx
> Hotfix: 타입 오류

- src/components/BookMange/BasicManage/DayNotion.tsx
- src/components/BookMange/DateMange/DateManage.tsx
- src/components/BookMange/TimeSelecter.tsx
> Fix: 타임 피커 이름 수정

- src/utils/instrumentUtils.ts
- 합주가 악기로 보이는 오류 수정
- closed #86
> Fix: 합주가 악기로 보이는 오류 수정

- src/pages/ManagePage.tsx
- (이곳에 PR을 작성한 이유를 간략하게 적어주세요.)
- closed #83 
- 
- 
-
> Style: 호버 색상

- src/components/Manage/DynamicTable.tsx
- src/components/Manage/ManageModal.tsx
- src/pages/SignUpPage.tsx
- 피드백 반영
- closed #84
- closed #85 
- 피드백 반영
- 
-
> Feat: 회원 탈퇴 모달 / 승인 대기 문구

- src/components/BookMange/DateMange/DateManage.tsx
- src/components/Manage/ApprovalTable.tsx
- src/components/Manage/DynamicTable.tsx
- 콘솔창에 민감한 정보가 노출 됨
- closed #95 
- 이제 더 이상 콘솔 창에 민감한 정보가 노출되지 않음
- 
-
> Fix: 민감한 정보 처리

- src/api/register.ts
- src/components/SignUp/SignUpForm.tsx
- 이메일 따닥 이슈
- closed #101
- 이메일만 변경
> Fix: 회원가입 이메일 처리 

- src/pages/HomePage.tsx
- (이곳에 PR을 작성한 이유를 간략하게 적어주세요.)
> Feat: 메인페이지 막기

- src/components/Home/Activity.tsx
- src/components/Home/Apply.tsx
- src/components/Home/YoutubeContents.tsx
- src/pages/HomePage.tsx
- 홈페이지 편하게 변경
- closed #109 
- 디자인 변경
> Style: 모바일 뷰 및 디자인 변경

- src/pages/ContactPage.tsx
- src/pages/RecruitPage.tsx
- 다른 페이지들에 copyright 하단 바 적용했습니다.
- 홈페이지와 지원하기, 문의하기 페이지에도 하단 바를 적용
> Feature: 다른 페이지에 copyright 하단 바 적용 

- src/components/Contact/ContactStyles.tsx
- src/pages/ContactPage.tsx
- 문의하기 페이지 디자인
- closed #114
- 문의하기 페이지 디자인
- 문의하기 페이지 디자인
- 디자인 피드백 받습니다
> Feat: 문의하기 페이지 디자인

- src/components/Login/LoginForm.tsx
- src/components/SignUp/SignUpForm.tsx
- 비밀번호 필드에서 CAPS LOCK 켜져 있을 때 경고 문구가 필요할 거 같아서
- closed #113
-
-
-
> Feature: CAPS LOCK 경고 문구

- src/components/SignUp/SignUpForm.tsx
- src/pages/SignUpPage.tsx
- 
- 
- 스타일 컴포넌트 개선, 타입 명시
- 
-
> Refactor: 회원가입 페이지 리팩토링

- src/api/emailAuth.ts
- src/components/SignUp/SignUpForm.tsx
- 이메일 인증 기능 추가
- 
- 
- 아직 인증번호 유효 시간 표시는 안 됨
-
> Feature: 이메일 인증

- src/components/Login/LoginForm.tsx
- src/components/Manage/ApprovalTable.tsx
- src/components/Manage/DynamicTable.tsx
- src/components/pages/LoginPage.tsx
- src/components/pages/ManagePage.tsx
> style: 스타일 코드 영역 분리

- package-lock.json
- src/components/HomePage/HomePageStyles.tsx
- src/components/LoginPage/LoginForm.tsx
- src/components/Mypage/MyPageStyles.tsx
- src/components/PasswordChange/PasswordChangeStyles.tsx
- src/components/PasswordChange/PasswordForm.tsx
- src/components/RecruitPage/RecruitPageStyles.tsx
- src/pages/HomePage.tsx
- src/pages/MyPage.tsx
- src/pages/PasswordChange.tsx
- src/pages/RecruitPage.tsx
- 마이페이지 & 비번 변경 페이지 & 비회원 페이지 스타일 코드 분리
- 비번 변경 페이지 기능 리펙토링 
- closed #149
> refactor: 스타일 코드 분리와 비번 변경 리펙토링

- src/api/Instance/authApi.ts
- src/api/Instance/baseApi.ts
- src/api/member.ts
- src/components/LoginPage/LoginForm.tsx
- src/data/user.ts
- 다음에 할게요
- 회원 정보 호출 로직 추가
- 회원 정보 호출 로직 추가
> Refactor: 회원 정보 호출 로직 추가

- src/api/Instance/authApi.ts
- src/components/LoginPage/LoginForm.tsx
- src/components/SignUpPage/SignUpForm.tsx
- vite.config.ts
> Fix: 로그인 폼 수정

- src/components/LoginPage/LoginForm.tsx
- src/contexts/AuthContext.tsx
- src/pages/MyPage.tsx
- 로컬 스토리지 배제를 허술하게 해서 다시 함
- 이번엔 진짜 성공함
> Fix/#179 memberstatus 2차 시도

- src/api/auth.ts
- src/components/PasswordChange/PasswordForm.tsx
- src/contexts/AuthContext.tsx
- src/utils/jwt.ts
- 배포 전 오류 해결
- #183 closes
- 로컬 스토리지 데이터 캐싱 방식 배제
- 비밀번호 변경 성공
- 빌드 성공
> Fix/#183 비밀 번호 변경 오류 해결

- src/api/auth.ts
- src/components/LoginPage/LoginForm.tsx
- src/components/PasswordChange/PasswordForm.tsx
- src/contexts/AuthContext.tsx
- src/pages/MyPage.tsx
- src/utils/jwt.ts
> Chore: 배포 전 비밀번호 변경 업데이트

- index.html
- src/api/member.ts
- src/components/LoginPage/LoginForm.tsx
- vercel.json
> Fix: 충돌 해결

- src/App.tsx
- src/api/auth.ts
- src/components/LoginPage/LoginForm.tsx
- src/components/PasswordReset/PasswordResetForm.tsx
- src/components/PasswordResetRedirect/PasswordResetRedirectForm.tsx
- src/components/SignUpPage/SignUpForm.tsx
- src/components/Toast.tsx
- src/pages/LoginPage.tsx
- src/pages/PasswordResetPage.tsx
- src/pages/PasswordResetRedirectPage.tsx
- src/pages/SignUpPage.tsx
- src/styles/Auth/Notice.ts
- src/styles/Auth/PageStyle.ts
- src/styles/Auth/SharedStyle.ts
- src/utils/useCapsLock.ts
- Closes #196 
- 비밀번호 변경, 리다이렉트 페이지 UI
- 필드 검사 커스텀 훅
- 토스트 컴포넌트
- 메일로 전송되는 링크에서 https://keunsori.com 이후 /password/change?key=... 부분을 복사해서 로컬 주소에 붙여서 테스트 하세요
- 배포 이후에는 자연스럽게 연결될 예정
> Feat: 비밀번호 찾기(초기화)

- src/components/Book/BookPage/Application/Reservation/Reservation.tsx
- src/components/Book/BookPage/Application/Reservation/TimeSlotsGrid.tsx
- src/components/BookManage/BasicManage/BasicManage.tsx
- src/styles/Book/Containers.ts
- src/styles/Book/Times.ts
- src/styles/NotionStyle.ts
- #205 
- string 타입에서 시간 문자열 TimeString 타입으로 수정했습니다.
- 다른 파일들 css 문법 오류도 수정했습니다. 
- (다른 리뷰어 들이 알아야할 상황)
> Fix: 시간 문자열 타입 오류 해결

- package-lock.json
- src/components/navBar/navBar.tsx
- close #218 
- my keun 인터랙션 라우팅 진입점 변경 (/book -> /login)
- 자동 로그인 기간이 늘어났을 때 어떤 식으로 대응할 지에 따라 변경 필요할 지도
> Fix: 앱 진입점 수정
